WITH CTE AS (
SELECT TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
DAYNAME(TO_TIMESTAMP(STARTED_AT)),
{{days_of_theweek('STARTED_AT') }}  AS DAY_TYPE,
MONTH(TO_TIMESTAMP(STARTED_AT)),
{{season_of_year('STARTED_AT') }} AS SEASON_OF_YEAR
 FROM {{ ref('stg_bike') }}
)

SELECT * FROM CTE 